name: ci-golang-workflow

on:
    [push]

jobs:
    check-application:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version: 1.5
            - run: go test
            - run: go run math.go
